version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gha-deps:
        patterns:
          - "*"
  - package-ecosystem: "mix"
    directory: "/"
    insecure-external-code-execution: "allow"
    schedule:
      interval: "weekly"
    groups:
      mix-deps:
        patterns:
          - "*"
